version: '3.8'
services:
  php:
    build: .
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    networks:
      - php-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
